{
 "title": "Ceph Cluster Performance",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Commit Latency",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(ceph_osd_commit_latency_ms)",
     "legendFormat": "Write Latency"
    }
   ]
  },
  {
   "title": "Commit Latency",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 11, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(ceph_osd_commit_latency_ms)",
     "legendFormat": "Write Latency"
    }
   ]
  },
  {
   "title": "Commit Latency",
   "type": "stat",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ceph_osd_commit_latency_ms", "legendFormat": "{{ceph_daemon}}" }
   ]
  },
  {
   "title": "Apply Latency",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(ceph_osd_apply_latency_ms)", "legendFormat": "Read/Write Latency" }
   ]
  },
  {
   "title": "Apply Latency",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 11, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "avg(ceph_osd_apply_latency_ms)", "legendFormat": "Read/Write Latency" }
   ]
  },
  {
   "title": "Apply Latency",
   "type": "stat",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ceph_osd_apply_latency_ms", "legendFormat": "{{ceph_daemon}}" }
   ]
  },
  { "title": "IOPs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Ceph Cluster IOPs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(ceph_pool_rd[5m]) + rate(ceph_pool_wr[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "IOPs Ceph Cluster (Read)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 3, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    { "expr": "sum(rate(ceph_pool_rd[5m]))", "legendFormat": "Read" }
   ]
  },
  {
   "title": "IOPs Ceph Cluster (Write)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 13, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    { "expr": "sum(rate(ceph_pool_wr[5m]))", "legendFormat": "Write" }
   ]
  },
  {
   "title": "IOPs (Read)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(rate(ceph_pool_rd[5m]))", "legendFormat": "Read" }
   ]
  },
  {
   "title": "IOPs (Write)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(rate(ceph_pool_wr[5m]))", "legendFormat": "Write" }
   ]
  },
  { "title": "Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Ceph Cluster Throughput",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(ceph_pool_rd_bytes[5m]) + rate(ceph_pool_wr_bytes[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster Throughput (Read)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 3, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(ceph_pool_rd_bytes[5m]))",
     "legendFormat": "Read"
    }
   ]
  },
  {
   "title": "Cluster Throughput (Write)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 13, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(ceph_pool_wr_bytes[5m]))",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Cluster Throughput (Read)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(ceph_pool_rd_bytes[5m]))",
     "legendFormat": "Read"
    }
   ]
  },
  {
   "title": "Cluster Throughput (Write)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(ceph_pool_wr_bytes[5m]))",
     "legendFormat": "Write"
    }
   ]
  }
 ]
}