{
 "title": "Ceph Service",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Ceph Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Ceph Health Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "max(ceph_health_status)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "mon.pve9node1",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceph_mon_quorum_status{ceph_daemon=\"mon.pve9node1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "mon.pve9node2",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceph_mon_quorum_status{ceph_daemon=\"mon.pve9node2\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "mon.pve9node3",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceph_mon_quorum_status{ceph_daemon=\"mon.pve9node3\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OSD Up",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(ceph_osd_up)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "OSD IN",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(ceph_osd_in)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "mgr.pve9node1",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceph_mgr_status{ceph_daemon=\"mgr.pve9node1\"}",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "mgr.pve9node2",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceph_mgr_status{ceph_daemon=\"mgr.pve9node2\"}",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "mgr.pve9node3",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceph_mgr_status{ceph_daemon=\"mgr.pve9node3\"}",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "OSD Down",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ceph_osd_up) - sum(ceph_osd_up)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OSD OUT",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ceph_osd_in) - sum(ceph_osd_in)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Ceph Status Threshold", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Ceph Health Status Alert",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 8 },
   "targets": [
    { "expr": "1 - max(ceph_health_status)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Ceph Mon Alert",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 8 },
   "targets": [
    { "expr": "ceph_mon_quorum_status", "legendFormat": "{{ceph_daemon}}" }
   ]
  },
  {
   "title": "Ceph Mgr Alert",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 8 },
   "targets": [
    { "expr": "ceph_mgr_status", "legendFormat": "{{ceph_daemon}}" }
   ]
  },
  {
   "title": "Ceph OSD Alert (UP / DOWN)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 17 },
   "targets": [
    { "expr": "ceph_osd_up", "legendFormat": "{{ceph_daemon}}" }
   ]
  },
  {
   "title": "Ceph OSD Alert (IN / OUT)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 17 },
   "targets": [
    { "expr": "ceph_osd_in", "legendFormat": "{{ceph_daemon}}" }
   ]
  }
 ]
}